version: "3.8"
services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: ${POSTGRES_CONTAINER}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pendant-sheet-unmixable
    volumes:
      - ${POSTGRES_PVC}:/var/lib/postgresql/data

  admin_server:
    build:
      context: ./service/
      dockerfile: Admin_Dockerfile
    image: ${ADMIN_SERVER_CONTAINER}
    ports:
      - ${ADMIN_FLASK_SERVICE_PORT}:${ADMIN_FLASK_SERVICE_PORT}
    environment:
      - DATABASE_PASSWORD=diffuser
    depends_on:
      - postgres

  student_server:
    build:
      context: ./service/
      dockerfile: Student_Dockerfile
    image: ${STUDENT_SERVER_CONTAINER}
    ports:
      - ${STUDENT_FLASK_SERVICE_PORT}:${STUDENT_FLASK_SERVICE_PORT}
    environment:
      - DATABASE_PASSWORD=capture
    depends_on:
      - postgres
