apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: admin-flask-{{.Values.Course.name | default "class"}}-ingress
spec:
  rules:
    - host: {{.Values.AdminFlask.host | default "engr131-admin-grader.nrp-nautilus.io"}} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-flask-{{.Values.Course.name | default "class"}}-service #ADMIN_FLASK_SERVICE_NAME
                port:
                  number: {{.Values.AdminFlask.port.number | default "5100"}} #ADMIN_FLASK_SERVICE_PORT
          - path: /logout
            pathType: Prefix
            backend:
              service:
                name: admin-flask-{{.Values.Course.name | default "class"}}-service #ADMIN_FLASK_SERVICE_NAME
                port:
                  number: {{.Values.AdminFlask.port.number | default "5100"}} #ADMIN_FLASK_SERVICE_PORT
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: admin-flask-{{.Values.Course.name | default "class"}}-service #ADMIN_FLASK_SERVICE_NAME
                port:
                  number: {{.Values.AdminFlask.port.number | default "5100"}}
          - path: /upload_assignment
            pathType: Prefix
            backend:
              service:
                name: admin-flask-{{.Values.Course.name | default "class"}}-service #ADMIN_FLASK_SERVICE_NAME
                port:
                  number: {{.Values.AdminFlask.port.number | default "5100"}} #ADMIN_FLASK_SERVICE_PORT
          - path: /upload_score
            pathType: Prefix
            backend:
              service:
                name: admin-flask-{{.Values.Course.name | default "class"}}-service #ADMIN_FLASK_SERVICE_NAME
                port:
                  number: {{.Values.AdminFlask.port.number | default "5100"}} #ADMIN_FLASK_SERVICE_PORT
          - path: /upload_students
            pathType: Prefix
            backend:
              service:
                name: admin-flask-{{.Values.Course.name | default "class"}}-flask-service #ADMIN_FLASK_SERVICE_NAME
                port:
                  number: {{.Values.AdminFlask.port.number | default "5100"}} #ADMIN_FLASK_SERVICE_PORT
  tls:
    - hosts:
        - engr131-admin-grader.nrp-nautilus.io #ADMIN_FLASK_HOSTNAME
