apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pgweb
  name: pgweb
spec:
  containers:
    - image: sosedoff/pgweb
      name: pgweb
      args: [
          "--bind=0.0.0.0",
          "--listen={{.Values.PGWeb.port | default "8081"}}", #PGWEB_PORT
          "--auth-user={{.Values.PGWeb.user | default "user"}}",
          "--auth-pass={{.Values.PGWeb.password | default "password"}}", #PGWEB_PASSWORD
          "--no-idle-timeout"
        ] # Corrected the syntax for the command line arguments
      ports:
        - containerPort: {{.Values.PGWeb.port | default "8081"}} #PGWEB_PORT
      env: # Corrected the placement and syntax for environment variables
        - name: PGWeb-{{.Values.Course.name | default "class"}} # Example environment variable name
          value: "pgweb" # Example environment variable value
      resources:
        limits:
          memory: "{{.Values.PGWeb.limits.memory | default "12Gi"}}"
          cpu: "{{.Values.PGWeb.limits.cpu | default "2"}}" 
        requests:
          memory: "{{.Values.PGWeb.requests.memory | default "6Gi"}}" 
          cpu: "{{.Values.PGWeb.requests.cpu | default "1"}}" 
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb-{{.Values.Course.name | default "class"}}-svc
  labels:
    service: pgweb-{{.Values.Course.name | default "class"}}-svc
spec:
  selector:
    run: pgweb # This selector must match the label on the Pod
  type: ClusterIP
  ports:
    - port: {{.Values.PGWeb.port | default "8081"}} # The port the service is exposed on
      targetPort: {{.Values.PGWeb.port | default "8081"}} # The port the container is listening on
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: pgweb-{{.Values.Course.name | default "class"}}-ingress
spec:
  rules:
    - host: {{.Values.PGWeb.host | default "pgqev-dev.nrp-nautilus.io"}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pgweb-{{.Values.Course.name | default "class"}}-svc # Corrected to the actual service name
                port:
                  number: {{.Values.PGWeb.port | default "8081"}}
  tls:
    - hosts:
        - {{.Values.PGWeb.host | default "pgqev-dev.nrp-nautilus.io"}}
