apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  selector:
    service: postgres
  type: ClusterIP
  ports:
    - port: '{{ .Values.Postgres.port.number | default "5432" }}' #POSTGRES_PORT
      targetPort: '{{ .Values.Postgres.port.number | default "5432" }}' # The port the container is listening on
