apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  user: {{ .Values.data.user | b64enc | quote | default c2FtcGxl}}
  password: {{ .Values.data.password | b64enc | quote | default cGxlYXNlY2hhbmdlbWU=}}
  student_pass: {{ .Values.data.student_pass | b64enc | quote | default Y2FwdHVyZQ==}}
  admin_pass: {{ .Values.data.admin_pass | b64enc | quote | default ZGlmZnVzZXI=}}
