# values.yaml

# Course settings
Course:
  name: "class" # default course name

# Postgres settings
Postgres:
  # Replica settings
  replicaCount: "1" # default number of replicas

  # Image settings
  image: "jagar2/grade_database:latest" # default Postgres image

  # Resource limits
  limits:
    memory: "12Gi" # maximum amount of memory the container can use
    cpu: "4" # maximum number of CPU units the container can use

  # Resource requests
  requests:
    memory: "6Gi" # minimum amount of memory required for the container to run
    cpu: "2" # minimum number of CPU units required for the container to run

  # Host settings
  host: "engr131-pg-dev.nrp-nautilus.io" # Default host for the Ingress

  # Port settings
  port:
    number: "5432" # Default service port

  storage: "5Gi"

  storageClassName: "rook-ceph-block"

# AdminFlask settings
AdminFlask:
  # Replica settings
  replicaCount: "2" # Default number of replicas for the Admin Flask server

  # Image settings
  image: "jagar2/admin_flask_server:2.0.5" # Default Docker image for the Admin Flask server

  # Resource limits
  limits:
    memory: "12Gi" # Maximum amount of memory the container can use
    cpu: "4" # Maximum number of CPU units the container can use

  # Resource requests
  requests:
    memory: "6Gi" # Minimum amount of memory required for the container to run
    cpu: "2" # Minimum number of CPU units required for the container to run

  # Host settings
  host: "engr131-admin-grader-dev.nrp-nautilus.io" # Default host for the Ingress

  # Port settings
  port:
    number: "5100" # Default service port

StudentFlask:
  host: "engr131-student-grader-dev.nrp-nautilus.io"
  port:
    number: "5200"
  replicaCount: 2
  limits:
    memory: "12Gi"
    cpu: "4"
  requests:
    memory: "6Gi"
    cpu: "2"
  image: "jagar2/student_flask_server:latest"

data:
  user: "c2FtcGxl" # base64 for "sample"
  password: "cGxlYXNlY2hhbmdlbWU=" # base64 for "pleasechange"
  student_pass: "Y2FwdHVyZQ==" # base64 for "capture"
  admin_pass: "ZGlmZnVzZXI=" # base64 for "diffuser"

PGWeb:
  port: 8081
  user: "user"
  password: "password"
  host: "pgweb-dev.nrp-nautilus.io"
  limits:
    memory: "12Gi"
    cpu: "2"
  requests:
    memory: "6Gi"
    cpu: "1"
