apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-josh
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: rook-ceph-block
