export OAUTH_CLIENT_SECRET="VsH4/qz0Vm+4pENMFP3j6EeyHgi4s1RPQNR7Mrp4Pxg="
export OAUTH_CALLBACK_URL="https://${course}-${semester}.${HOSTNAME}/hub/oauth_callback"
export OAUTH_CLIENT_ID="e34feab7-6074-4b9d-8122-b75ae6757e4d"

hub:
  config:
    JupyterHub:
      admin_access: true
      admin_users: ${ADMIN_LIST}
      authenticator_class: "oauthenticator.globus.GlobusOAuthenticator" # Corrected class name
    GlobusOAuthenticator:
      client_id: ${OAUTH_CLIENT_ID} # Your Globus client ID
      client_secret: ${OAUTH_CLIENT_SECRET} # Your Globus client secret
      oauth_callback_url: ${OAUTH_CALLBACK_URL} # Ensure this matches the callback URL registered in Globus
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  deploymentStrategy:
    type: Recreate
  db:
    type: sqlite-pvc
    pvc:
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      storageClassName: rook-ceph-east
  resources:
    limits:
      cpu: 3
      memory: 3Gi
    requests:
      cpu: 1
      memory: 1Mi
  networkPolicy:
    enabled: false
proxy:
  secretToken: "26dc96fa434719ef7e8012338ad6d84f4808a9510e1bd839108de457da763fa5"
  service:
    type: ClusterIP
  chp:
    resources:
      limits:
        cpu: "6"
        memory: 2Gi
      requests:
        cpu: 2
        memory: 1Gi
singleuser:
  extraPodConfig:
    securityContext:
      fsGroupChangePolicy: "OnRootMismatch"
      fsGroup: 100
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
  storage:
    type: dynamic
    extraLabels: {}
    extraVolumes: []
    extraVolumeMounts: []
    capacity: 0.5Gi
    homeMountPath: /home/jovyan
    dynamic:
      storageClass: rook-ceph-east
      pvcNameTemplate: claim-{username}{servername}
      volumeNameTemplate: volume-{username}{servername}
      storageAccessModes: [ReadWriteOnce]
  image:
    name: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp
    tag: latest
  startTimeout: 600
  cpu:
    limit: 6
    guarantee: 1
  memory:
    limit: 10G
    guarantee: 10G
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl: "/lab"
  profileList:
    - display_name: ENGR131
      kubespawner_override:
        image_spec: jagar2/engr_131_jupyter_hub:1.0.6

scheduling:
  podPriority:
    enabled: false # Enable pod priority
  userScheduler:
    enabled: false
  userPlaceholder:
    enabled: true
    replicas: 2

# prePuller relates to the hook|continuous-image-puller DaemonsSets
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
  hosts: ["engr131-spring2024.nrp-nautilus.io"]
  pathSuffix: ""
  tls:
    - hosts:
        - engr131-spring2024.nrp-nautilus.io

cull:
  enabled: true
  users: true
  removeNamedServers: true
  timeout: 3600
  every: 600
  concurrency: 10
  maxAge: 86400
